alter table "public"."posts" drop constraint "Post_uid_key";

alter table "public"."posts" drop constraint "unique_posts_ghost_id";

drop index if exists "public"."Post_uid_5c70a06a_like";

drop index if exists "public"."Post_uid_key";

drop index if exists "public"."idx_ghost_id";

drop index if exists "public"."unique_posts_ghost_id";

alter table "public"."posts" drop column "ghost_id";

alter table "public"."posts" drop column "is_cn";

alter table "public"."posts" drop column "is_important";

alter table "public"."posts" drop column "uid";

alter table "public"."posts" alter column "id" drop default;

alter table "public"."posts" alter column "id" add generated by default as identity;

alter table "public"."posts_raw" drop column "categories";

alter table "public"."posts_raw" drop column "is_cn";

alter table "public"."posts_raw" drop column "tags";

alter table "public"."tags" drop column "name_cn";
