create table "public"."configs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "key" character varying not null default ''::character varying,
    "value" jsonb
);


alter table "public"."configs" enable row level security;

CREATE UNIQUE INDEX configs_key_key ON public.configs USING btree (key);

CREATE UNIQUE INDEX configs_pkey ON public.configs USING btree (id);

alter table "public"."configs" add constraint "configs_pkey" PRIMARY KEY using index "configs_pkey";

alter table "public"."configs" add constraint "configs_key_key" UNIQUE using index "configs_key_key";

grant delete on table "public"."configs" to "anon";

grant insert on table "public"."configs" to "anon";

grant references on table "public"."configs" to "anon";

grant select on table "public"."configs" to "anon";

grant trigger on table "public"."configs" to "anon";

grant truncate on table "public"."configs" to "anon";

grant update on table "public"."configs" to "anon";

grant delete on table "public"."configs" to "authenticated";

grant insert on table "public"."configs" to "authenticated";

grant references on table "public"."configs" to "authenticated";

grant select on table "public"."configs" to "authenticated";

grant trigger on table "public"."configs" to "authenticated";

grant truncate on table "public"."configs" to "authenticated";

grant update on table "public"."configs" to "authenticated";

grant delete on table "public"."configs" to "service_role";

grant insert on table "public"."configs" to "service_role";

grant references on table "public"."configs" to "service_role";

grant select on table "public"."configs" to "service_role";

grant trigger on table "public"."configs" to "service_role";

grant truncate on table "public"."configs" to "service_role";

grant update on table "public"."configs" to "service_role";
