drop policy "Enable read access for all users" on "public"."posts_secrets";

revoke delete on table "public"."posts_secrets" from "anon";

revoke insert on table "public"."posts_secrets" from "anon";

revoke references on table "public"."posts_secrets" from "anon";

revoke select on table "public"."posts_secrets" from "anon";

revoke trigger on table "public"."posts_secrets" from "anon";

revoke truncate on table "public"."posts_secrets" from "anon";

revoke update on table "public"."posts_secrets" from "anon";

revoke delete on table "public"."posts_secrets" from "authenticated";

revoke insert on table "public"."posts_secrets" from "authenticated";

revoke references on table "public"."posts_secrets" from "authenticated";

revoke select on table "public"."posts_secrets" from "authenticated";

revoke trigger on table "public"."posts_secrets" from "authenticated";

revoke truncate on table "public"."posts_secrets" from "authenticated";

revoke update on table "public"."posts_secrets" from "authenticated";

revoke delete on table "public"."posts_secrets" from "service_role";

revoke insert on table "public"."posts_secrets" from "service_role";

revoke references on table "public"."posts_secrets" from "service_role";

revoke select on table "public"."posts_secrets" from "service_role";

revoke trigger on table "public"."posts_secrets" from "service_role";

revoke truncate on table "public"."posts_secrets" from "service_role";

revoke update on table "public"."posts_secrets" from "service_role";

alter table "public"."posts_categories" drop constraint "posts_categories_post_id_fkey";

alter table "public"."posts_tags" drop constraint "posts_tags_post_id_fkey";

drop view if exists "public"."v_posts";

alter table "public"."posts_categories" drop constraint "posts_categories_pkey";

alter table "public"."posts_secrets" drop constraint "posts_secrets_pkey";

alter table "public"."posts_tags" drop constraint "posts_tags_pkey";

drop index if exists "public"."posts_categories_pkey";

drop index if exists "public"."posts_secrets_pkey";

drop index if exists "public"."posts_tags_pkey";

drop table "public"."posts_secrets";

alter table "public"."posts" add column "id2" bigint generated by default as identity not null;

alter table "public"."posts_categories" drop column "post_id";

alter table "public"."posts_tags" drop column "post_id";
