
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "citext" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "moddatetime" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE TYPE "public"."ads_position" AS ENUM (
    'sides',
    'banner',
    'right-sticky'
);

ALTER TYPE "public"."ads_position" OWNER TO "postgres";

CREATE TYPE "public"."type" AS ENUM (
    'navi',
    'promo',
    'spider',
    'undo',
    'unknown'
);

ALTER TYPE "public"."type" OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."create_tags_name_cn"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  IF NEW.name_cn IS NULL OR NEW.name_cn = '' THEN
    NEW.name_cn := NEW.name;
  END IF;
  RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."create_tags_name_cn"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."generate_uid"() RETURNS "text"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
  chars text[] := array[
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
    'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
    'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
    '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'
  ];
  uid text := '';
BEGIN
  FOR i IN 1..8 LOOP
    uid := uid || chars[1 + round(random() * (array_length(chars, 1) - 1))];
  END LOOP;
  RETURN uid;
END;
$$;

ALTER FUNCTION "public"."generate_uid"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."update_tag_count"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  -- 处理插入操作
  IF TG_OP = 'INSERT' THEN
    UPDATE tags
    SET count = count + 1
    WHERE id = NEW.tag_id;
  -- 处理删除操作
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE tags
    SET count = count - 1
    WHERE id = OLD.tag_id;
  -- 处理更新操作
  ELSIF TG_OP = 'UPDATE' THEN
    -- 当标签ID发生变化时，更新旧标签和新标签的计数字段
    IF OLD.tag_id <> NEW.tag_id THEN
      UPDATE tags
      SET count = count - 1
      WHERE id = OLD.tag_id;

      UPDATE tags
      SET count = count + 1
      WHERE id = NEW.tag_id;
    END IF;
  END IF;

  RETURN NULL;
END;
$$;

ALTER FUNCTION "public"."update_tag_count"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."ads" (
    "id" bigint NOT NULL,
    "site_id" bigint NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "position" "public"."ads_position" DEFAULT 'banner'::"public"."ads_position" NOT NULL,
    "end_at" timestamp with time zone
);

ALTER TABLE "public"."ads" OWNER TO "postgres";

ALTER TABLE "public"."ads" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ads_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."autolinks" (
    "id" bigint NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "keyword" character varying DEFAULT ''::character varying NOT NULL,
    "url" character varying DEFAULT ''::character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."autolinks" OWNER TO "postgres";

ALTER TABLE "public"."autolinks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."autolinks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."categories" (
    "id" bigint NOT NULL,
    "name" character varying DEFAULT ''::character varying NOT NULL,
    "description" character varying DEFAULT ''::character varying NOT NULL,
    "slug" character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."categories" OWNER TO "postgres";

ALTER TABLE "public"."categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."cons" (
    "id" bigint NOT NULL,
    "content" character varying DEFAULT ''::character varying NOT NULL,
    "content_cn" character varying DEFAULT ''::character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "order" smallint DEFAULT '0'::smallint NOT NULL
);

ALTER TABLE "public"."cons" OWNER TO "postgres";

ALTER TABLE "public"."cons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."cryptos" (
    "id" bigint NOT NULL,
    "created_at" timestamp(6) with time zone NOT NULL,
    "updated_at" timestamp(6) with time zone NOT NULL,
    "is_active" boolean NOT NULL,
    "order" integer NOT NULL,
    "name" character varying(30) NOT NULL,
    "shortcode" character varying(10) NOT NULL,
    "description" character varying(200) NOT NULL,
    "avatar" character varying(200) NOT NULL,
    "avatar_source" character varying(200) NOT NULL
);

ALTER TABLE "public"."cryptos" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."cryptos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."cryptos_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."cryptos_id_seq" OWNED BY "public"."cryptos"."id";

CREATE TABLE IF NOT EXISTS "public"."delivers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "domains" "jsonb" NOT NULL,
    "mail_id" bigint,
    "site_id" bigint NOT NULL
);

ALTER TABLE "public"."delivers" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."delivers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."delivers_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."delivers_id_seq" OWNED BY "public"."delivers"."id";

CREATE TABLE IF NOT EXISTS "public"."filters" (
    "id" bigint NOT NULL,
    "created_at" timestamp(6) with time zone NOT NULL,
    "updated_at" timestamp(6) with time zone NOT NULL,
    "is_active" boolean NOT NULL,
    "order" integer NOT NULL,
    "description" "text" NOT NULL,
    "supplement" "text" NOT NULL,
    "navigation_id" bigint NOT NULL,
    "tag1_id" bigint NOT NULL,
    "tag2_id" bigint NOT NULL
);

ALTER TABLE "public"."filters" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."filters_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."filters_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."filters_id_seq" OWNED BY "public"."filters"."id";

CREATE TABLE IF NOT EXISTS "public"."images" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "source" character varying(250),
    "url" character varying DEFAULT ''::character varying NOT NULL,
    "description" character varying DEFAULT ''::character varying NOT NULL,
    "hash" character varying
);

ALTER TABLE "public"."images" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."mails" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "address" character varying(20) NOT NULL
);

ALTER TABLE "public"."mails" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."navigations" (
    "id" bigint NOT NULL,
    "created_at" timestamp(6) with time zone NOT NULL,
    "updated_at" timestamp(6) with time zone NOT NULL,
    "is_active" boolean NOT NULL,
    "order" integer NOT NULL,
    "name" character varying(20) NOT NULL
);

ALTER TABLE "public"."navigations" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."navigations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."navigations_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."navigations_id_seq" OWNED BY "public"."navigations"."id";

CREATE TABLE IF NOT EXISTS "public"."navis" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "is_active" boolean NOT NULL,
    "order" integer NOT NULL,
    "title" character varying(100) NOT NULL,
    "url" character varying(150) NOT NULL,
    "deliver_id" bigint,
    "name" character varying(20) NOT NULL
);

ALTER TABLE "public"."navis" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."navis_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."navis_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."navis_id_seq" OWNED BY "public"."navis"."id";

CREATE TABLE IF NOT EXISTS "public"."payments" (
    "id" bigint NOT NULL,
    "name" character varying DEFAULT ''::character varying NOT NULL,
    "name_cn" character varying DEFAULT ''::character varying NOT NULL,
    "logo" character varying,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."payments" OWNER TO "postgres";

ALTER TABLE "public"."payments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."payments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."posts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "uid" character varying(8) NOT NULL,
    "title" character varying(200) DEFAULT ''::character varying NOT NULL,
    "excerpt" character varying DEFAULT ''::character varying NOT NULL,
    "html" "text",
    "is_active" boolean DEFAULT false NOT NULL,
    "is_important" boolean DEFAULT false NOT NULL,
    "is_cn" boolean DEFAULT false NOT NULL,
    "featured_image" character varying,
    "visited" bigint DEFAULT '0'::bigint NOT NULL,
    "slug" character varying DEFAULT ''::character varying NOT NULL,
    "keywords" character varying,
    "ghost_id" character varying,
    "author_id" "uuid"
);

ALTER TABLE "public"."posts" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."posts_categories" (
    "post_id" bigint NOT NULL,
    "category_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."posts_categories" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."posts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."posts_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."posts_id_seq" OWNED BY "public"."posts"."id";

CREATE TABLE IF NOT EXISTS "public"."posts_raw" (
    "id" bigint NOT NULL,
    "post_id" bigint,
    "title" character varying DEFAULT ''::character varying NOT NULL,
    "excerpt" character varying DEFAULT ''::character varying NOT NULL,
    "keywords" character varying[],
    "featured_image" character varying,
    "html" "text",
    "tags" character varying[],
    "categories" character varying[],
    "is_cn" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "source" character varying,
    "secrets" "jsonb",
    "markdown" "text",
    "slug" character varying,
    "author_id" "uuid",
    "is_verified" boolean DEFAULT true NOT NULL
);

ALTER TABLE "public"."posts_raw" OWNER TO "postgres";

ALTER TABLE "public"."posts_raw" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."posts_raw_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."posts_secrets" (
    "id" bigint NOT NULL,
    "version" character varying,
    "data" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "post_id" bigint NOT NULL
);

ALTER TABLE "public"."posts_secrets" OWNER TO "postgres";

ALTER TABLE "public"."posts_secrets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."posts_secrets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."posts_sites" (
    "post_id" bigint NOT NULL,
    "site_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."posts_sites" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."posts_tags" (
    "post_id" bigint NOT NULL,
    "tag_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."posts_tags" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."promos" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "is_active" boolean NOT NULL,
    "order" integer NOT NULL,
    "uid" character varying(8) NOT NULL,
    "bonus" character varying(100) NOT NULL,
    "code" character varying(20) NOT NULL,
    "url" character varying(250) NOT NULL,
    "url_short" character varying(250) NOT NULL,
    "site_id" bigint NOT NULL,
    "bonus_cn" character varying DEFAULT ''::character varying NOT NULL
);

ALTER TABLE "public"."promos" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."promos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."promos_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."promos_id_seq" OWNED BY "public"."promos"."id";

CREATE TABLE IF NOT EXISTS "public"."pros" (
    "id" bigint NOT NULL,
    "content" character varying DEFAULT ''::character varying NOT NULL,
    "content_cn" character varying DEFAULT ''::character varying NOT NULL,
    "order" smallint DEFAULT '0'::smallint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."pros" OWNER TO "postgres";

ALTER TABLE "public"."pros" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pros_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."sites" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "is_active" boolean DEFAULT false NOT NULL,
    "order" integer DEFAULT 0 NOT NULL,
    "uid" character varying(8) NOT NULL,
    "name" character varying(150) DEFAULT ''::character varying NOT NULL,
    "short_name" "extensions"."citext",
    "avatar" character varying(200),
    "banner" character varying(200),
    "description" "text" DEFAULT ''::"text" NOT NULL,
    "rating" numeric(3,2) DEFAULT '3'::numeric NOT NULL,
    "url_source" character varying(250) DEFAULT ''::character varying NOT NULL,
    "type" "public"."type" DEFAULT 'unknown'::"public"."type" NOT NULL,
    "is_cn" boolean DEFAULT false NOT NULL,
    "is_lower_priority" boolean DEFAULT false NOT NULL,
    "short_description" character varying DEFAULT ''::character varying NOT NULL,
    "description_cn" character varying DEFAULT ''::character varying NOT NULL,
    "name_cn" character varying DEFAULT ''::character varying NOT NULL,
    "short_description_cn" character varying DEFAULT ''::character varying NOT NULL,
    "background_style" "json" DEFAULT '{}'::"json" NOT NULL,
    "keywords" character varying DEFAULT ''::character varying NOT NULL,
    "is_secondary_domain" boolean DEFAULT false NOT NULL,
    "alias" character varying[],
    "domains" character varying[],
    "is_recommended" boolean DEFAULT false NOT NULL,
    "square_image" character varying,
    "sides_image" character varying
);

ALTER TABLE "public"."sites" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."sites_categories" (
    "site_id" bigint NOT NULL,
    "category_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."sites_categories" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."sites_configs" (
    "id" bigint NOT NULL,
    "site_id" bigint NOT NULL,
    "email" character varying DEFAULT 'dota2sites@gmail.com'::character varying NOT NULL,
    "page_size" smallint DEFAULT '10'::smallint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "footer" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "header" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL
);

ALTER TABLE "public"."sites_configs" OWNER TO "postgres";

ALTER TABLE "public"."sites_configs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sites_configs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."sites_cons" (
    "site_id" bigint NOT NULL,
    "con_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."sites_cons" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."sites_cryptos" (
    "site_id" bigint NOT NULL,
    "crypto_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."sites_cryptos" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."sites_detail_posts" (
    "site_id" bigint NOT NULL,
    "post_id" bigint NOT NULL,
    "order" smallint DEFAULT '0'::smallint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."sites_detail_posts" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."sites_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."sites_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."sites_id_seq" OWNED BY "public"."sites"."id";

CREATE TABLE IF NOT EXISTS "public"."sites_payments" (
    "site_id" bigint NOT NULL,
    "payment_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."sites_payments" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."sites_pros" (
    "site_id" bigint NOT NULL,
    "pro_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."sites_pros" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."sites_tags" (
    "site_id" bigint NOT NULL,
    "tag_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."sites_tags" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."sites_tips" (
    "id" bigint NOT NULL,
    "site_id" bigint NOT NULL,
    "content" character varying DEFAULT ''::character varying NOT NULL,
    "count" bigint DEFAULT '0'::bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."sites_tips" OWNER TO "postgres";

ALTER TABLE "public"."sites_tips" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sites_tips_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."sites_visits" (
    "id" bigint NOT NULL,
    "site_id" bigint NOT NULL,
    "ip" character varying DEFAULT ''::character varying NOT NULL,
    "user_agent" character varying DEFAULT ''::character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "headers" "jsonb"
);

ALTER TABLE "public"."sites_visits" OWNER TO "postgres";

ALTER TABLE "public"."sites_visits" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sites_visits_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" bigint NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT "now"() NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "order" integer DEFAULT 0 NOT NULL,
    "name" character varying DEFAULT ''::character varying NOT NULL,
    "slug" character varying NOT NULL,
    "description" character varying DEFAULT ''::character varying NOT NULL,
    "count" integer DEFAULT 0 NOT NULL,
    "name_cn" character varying DEFAULT ''::character varying NOT NULL
);

ALTER TABLE "public"."tags" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."tags_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."tags_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."tags_id_seq" OWNED BY "public"."tags"."id";

CREATE SEQUENCE IF NOT EXISTS "public"."tmr_image_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."tmr_image_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."tmr_image_id_seq" OWNED BY "public"."images"."id";

CREATE SEQUENCE IF NOT EXISTS "public"."tmr_mail_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."tmr_mail_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."tmr_mail_id_seq" OWNED BY "public"."mails"."id";

CREATE OR REPLACE VIEW "public"."v_posts" AS
SELECT
    NULL::bigint AS "id",
    NULL::character varying(8) AS "uid",
    NULL::character varying(200) AS "title",
    NULL::character varying AS "excerpt",
    NULL::character varying AS "slug",
    NULL::character varying AS "ghost_id",
    NULL::character varying AS "featured_image",
    NULL::boolean AS "is_important",
    NULL::boolean AS "is_cn",
    NULL::boolean AS "is_active",
    NULL::"text" AS "html",
    NULL::timestamp with time zone AS "updated_at",
    NULL::timestamp with time zone AS "created_at",
    NULL::character varying[] AS "categories";

ALTER TABLE "public"."v_posts" OWNER TO "postgres";

CREATE OR REPLACE VIEW "public"."v_sites" AS
SELECT
    NULL::bigint AS "id",
    NULL::timestamp with time zone AS "created_at",
    NULL::timestamp with time zone AS "updated_at",
    NULL::boolean AS "is_active",
    NULL::integer AS "order",
    NULL::character varying(150) AS "name",
    NULL::character varying AS "name_cn",
    NULL::"extensions"."citext" AS "short_name",
    NULL::character varying(200) AS "avatar",
    NULL::character varying(200) AS "banner",
    NULL::"text" AS "description",
    NULL::character varying AS "description_cn",
    NULL::numeric(3,2) AS "rating",
    NULL::character varying(250) AS "url_source",
    NULL::"public"."type" AS "type",
    NULL::boolean AS "is_cn",
    NULL::boolean AS "is_lower_priority",
    NULL::character varying AS "short_description",
    NULL::character varying AS "short_description_cn",
    NULL::"json" AS "background_style",
    NULL::character varying AS "keywords",
    NULL::boolean AS "is_secondary_domain",
    NULL::character varying[] AS "alias",
    NULL::character varying[] AS "domains",
    NULL::boolean AS "is_recommended",
    NULL::character varying AS "square_image",
    NULL::character varying AS "sides_image",
    NULL::character varying(8) AS "uid",
    NULL::character varying(20) AS "code",
    NULL::character varying(100) AS "bonus",
    NULL::character varying AS "bonus_cn",
    NULL::character varying(250) AS "url",
    NULL::character varying[] AS "categories";

ALTER TABLE "public"."v_sites" OWNER TO "postgres";

ALTER TABLE ONLY "public"."cryptos" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."cryptos_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."delivers" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."delivers_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."filters" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."filters_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."images" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."tmr_image_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."mails" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."tmr_mail_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."navigations" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."navigations_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."navis" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."navis_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."posts" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."posts_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."promos" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."promos_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."sites" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."sites_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."tags" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."tags_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."cryptos"
    ADD CONSTRAINT "Crypto_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."filters"
    ADD CONSTRAINT "Filter_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."navigations"
    ADD CONSTRAINT "Navigation_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."posts"
    ADD CONSTRAINT "Post_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."posts"
    ADD CONSTRAINT "Post_uid_key" UNIQUE ("uid");

ALTER TABLE ONLY "public"."sites"
    ADD CONSTRAINT "Site_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."sites"
    ADD CONSTRAINT "Site_uid_key" UNIQUE ("uid");

ALTER TABLE ONLY "public"."ads"
    ADD CONSTRAINT "ads_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."autolinks"
    ADD CONSTRAINT "autolinks_keyword_key" UNIQUE ("keyword");

ALTER TABLE ONLY "public"."autolinks"
    ADD CONSTRAINT "autolinks_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_slug_key" UNIQUE ("slug");

ALTER TABLE ONLY "public"."cons"
    ADD CONSTRAINT "cons_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."delivers"
    ADD CONSTRAINT "delivers_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."navis"
    ADD CONSTRAINT "navis_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."payments"
    ADD CONSTRAINT "payments_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."posts_categories"
    ADD CONSTRAINT "posts_categories_pkey" PRIMARY KEY ("post_id", "category_id");

ALTER TABLE ONLY "public"."posts_raw"
    ADD CONSTRAINT "posts_raw_from_key" UNIQUE ("source");

ALTER TABLE ONLY "public"."posts_raw"
    ADD CONSTRAINT "posts_raw_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."posts_raw"
    ADD CONSTRAINT "posts_raw_post_id_key" UNIQUE ("post_id");

ALTER TABLE ONLY "public"."posts_sites"
    ADD CONSTRAINT "posts_related_sites_pkey" PRIMARY KEY ("post_id", "site_id");

ALTER TABLE ONLY "public"."posts_secrets"
    ADD CONSTRAINT "posts_secrets_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."posts_tags"
    ADD CONSTRAINT "posts_tags_pkey" PRIMARY KEY ("post_id", "tag_id");

ALTER TABLE ONLY "public"."promos"
    ADD CONSTRAINT "promos_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."promos"
    ADD CONSTRAINT "promos_uid_key" UNIQUE ("uid");

ALTER TABLE ONLY "public"."pros"
    ADD CONSTRAINT "pros_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."sites_categories"
    ADD CONSTRAINT "sites_categories_pkey" PRIMARY KEY ("site_id", "category_id");

ALTER TABLE ONLY "public"."sites_configs"
    ADD CONSTRAINT "sites_configs_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."sites_configs"
    ADD CONSTRAINT "sites_configs_site_id_key" UNIQUE ("site_id");

ALTER TABLE ONLY "public"."sites_cons"
    ADD CONSTRAINT "sites_cons_pkey" PRIMARY KEY ("site_id", "con_id");

ALTER TABLE ONLY "public"."sites_cryptos"
    ADD CONSTRAINT "sites_cryptos_pkey" PRIMARY KEY ("site_id", "crypto_id");

ALTER TABLE ONLY "public"."sites_detail_posts"
    ADD CONSTRAINT "sites_detail_posts_pkey" PRIMARY KEY ("site_id", "post_id");

ALTER TABLE ONLY "public"."sites_payments"
    ADD CONSTRAINT "sites_payments_pkey" PRIMARY KEY ("site_id", "payment_id");

ALTER TABLE ONLY "public"."sites_pros"
    ADD CONSTRAINT "sites_pros_pkey" PRIMARY KEY ("site_id", "pro_id");

ALTER TABLE ONLY "public"."sites"
    ADD CONSTRAINT "sites_short_name_unique" UNIQUE ("short_name");

ALTER TABLE ONLY "public"."sites_tags"
    ADD CONSTRAINT "sites_tags_pkey" PRIMARY KEY ("site_id", "tag_id");

ALTER TABLE ONLY "public"."sites_tips"
    ADD CONSTRAINT "sites_tips_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."sites_visits"
    ADD CONSTRAINT "sites_visits_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."images"
    ADD CONSTRAINT "source_unique" UNIQUE ("source");

ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_uri_928cdc64_uniq" UNIQUE ("slug");

ALTER TABLE ONLY "public"."images"
    ADD CONSTRAINT "tmr_image_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."mails"
    ADD CONSTRAINT "tmr_mail_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."posts_secrets"
    ADD CONSTRAINT "unique_post_id" UNIQUE ("post_id");

ALTER TABLE ONLY "public"."posts"
    ADD CONSTRAINT "unique_posts_ghost_id" UNIQUE ("ghost_id");

ALTER TABLE ONLY "public"."posts"
    ADD CONSTRAINT "unique_posts_slug" UNIQUE ("slug");

ALTER TABLE ONLY "public"."images"
    ADD CONSTRAINT "url_unique" UNIQUE ("url");

CREATE INDEX "Filter_navigation_id_532b6598" ON "public"."filters" USING "btree" ("navigation_id");

CREATE INDEX "Filter_tag1_id_b3dada88" ON "public"."filters" USING "btree" ("tag1_id");

CREATE INDEX "Filter_tag2_id_135903aa" ON "public"."filters" USING "btree" ("tag2_id");

CREATE INDEX "Post_uid_5c70a06a_like" ON "public"."posts" USING "btree" ("uid" "varchar_pattern_ops");

CREATE INDEX "Site_uid_7fad8fc5_like" ON "public"."sites" USING "btree" ("uid" "varchar_pattern_ops");

CREATE INDEX "delivers_mail_id_9875fa82" ON "public"."delivers" USING "btree" ("mail_id");

CREATE INDEX "delivers_site_id_228028f3" ON "public"."delivers" USING "btree" ("site_id");

CREATE INDEX "idx_create_time" ON "public"."posts" USING "btree" ("created_at");

CREATE INDEX "idx_ghost_id" ON "public"."posts" USING "btree" ("ghost_id");

CREATE INDEX "idx_slug" ON "public"."posts" USING "btree" ("slug");

CREATE INDEX "navis_deliver_id_7014b881" ON "public"."navis" USING "btree" ("deliver_id");

CREATE INDEX "promos_site_id_ddece13b" ON "public"."promos" USING "btree" ("site_id");

CREATE INDEX "promos_uid_91c375e6_like" ON "public"."promos" USING "btree" ("uid" "varchar_pattern_ops");

CREATE INDEX "tags_uri_928cdc64_like" ON "public"."tags" USING "btree" ("slug" "varchar_pattern_ops");

CREATE OR REPLACE VIEW "public"."v_sites" AS
 SELECT "s"."id",
    "s"."created_at",
    "s"."updated_at",
    "s"."is_active",
    "s"."order",
    "s"."name",
    "s"."name_cn",
    "s"."short_name",
    "s"."avatar",
    "s"."banner",
    "s"."description",
    "s"."description_cn",
    "s"."rating",
    "s"."url_source",
    "s"."type",
    "s"."is_cn",
    "s"."is_lower_priority",
    "s"."short_description",
    "s"."short_description_cn",
    "s"."background_style",
    "s"."keywords",
    "s"."is_secondary_domain",
    "s"."alias",
    "s"."domains",
    "s"."is_recommended",
    "s"."square_image",
    "s"."sides_image",
    "rp"."uid",
    "rp"."code",
    "rp"."bonus",
    "rp"."bonus_cn",
    "rp"."url",
    "array_agg"("c"."slug") FILTER (WHERE ("c"."slug" IS NOT NULL)) AS "categories"
   FROM ((("public"."sites" "s"
     LEFT JOIN ( SELECT "p"."site_id",
            "p"."uid",
            "p"."code",
            "p"."bonus",
            "p"."bonus_cn",
            "p"."url",
            "row_number"() OVER (PARTITION BY "p"."site_id" ORDER BY "p"."id") AS "rn"
           FROM "public"."promos" "p") "rp" ON ((("s"."id" = "rp"."site_id") AND ("rp"."rn" = 1))))
     LEFT JOIN "public"."sites_categories" "pc" ON (("s"."id" = "pc"."site_id")))
     LEFT JOIN "public"."categories" "c" ON (("pc"."category_id" = "c"."id")))
  GROUP BY "s"."id", "rp"."uid", "rp"."code", "rp"."bonus", "rp"."bonus_cn", "rp"."url";

CREATE OR REPLACE VIEW "public"."v_posts" AS
 SELECT "p"."id",
    "p"."uid",
    "p"."title",
    "p"."excerpt",
    "p"."slug",
    "p"."ghost_id",
    "p"."featured_image",
    "p"."is_important",
    "p"."is_cn",
    "p"."is_active",
    "p"."html",
    "p"."updated_at",
    "p"."created_at",
    "array_agg"("c"."slug") AS "categories"
   FROM (("public"."posts" "p"
     LEFT JOIN "public"."posts_categories" "pc" ON (("p"."id" = "pc"."post_id")))
     LEFT JOIN "public"."categories" "c" ON (("pc"."category_id" = "c"."id")))
  GROUP BY "p"."id";

CREATE OR REPLACE TRIGGER "update_name_cn_trigger" BEFORE INSERT ON "public"."tags" FOR EACH ROW EXECUTE FUNCTION "public"."create_tags_name_cn"();

CREATE OR REPLACE TRIGGER "update_tag_count_trigger" AFTER INSERT OR DELETE OR UPDATE ON "public"."posts_tags" FOR EACH ROW EXECUTE FUNCTION "public"."update_tag_count"();

ALTER TABLE ONLY "public"."ads"
    ADD CONSTRAINT "ads_site_id_fkey" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."delivers"
    ADD CONSTRAINT "delivers_mail_id_9875fa82_fk_tmr_mail_id" FOREIGN KEY ("mail_id") REFERENCES "public"."mails"("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY "public"."delivers"
    ADD CONSTRAINT "delivers_site_id_228028f3_fk_sites_id" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY "public"."filters"
    ADD CONSTRAINT "filters_navigation_id_fkey" FOREIGN KEY ("navigation_id") REFERENCES "public"."navigations"("id");

ALTER TABLE ONLY "public"."filters"
    ADD CONSTRAINT "filters_tag1_id_fkey" FOREIGN KEY ("tag1_id") REFERENCES "public"."tags"("id");

ALTER TABLE ONLY "public"."filters"
    ADD CONSTRAINT "filters_tag2_id_fkey" FOREIGN KEY ("tag2_id") REFERENCES "public"."tags"("id");

ALTER TABLE ONLY "public"."navis"
    ADD CONSTRAINT "navis_deliver_id_fkey" FOREIGN KEY ("deliver_id") REFERENCES "public"."delivers"("id");

ALTER TABLE ONLY "public"."posts"
    ADD CONSTRAINT "posts_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."posts_categories"
    ADD CONSTRAINT "posts_categories_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."posts_categories"
    ADD CONSTRAINT "posts_categories_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."posts_raw"
    ADD CONSTRAINT "posts_raw_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."posts_raw"
    ADD CONSTRAINT "posts_raw_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."posts_secrets"
    ADD CONSTRAINT "posts_secrets_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."posts_sites"
    ADD CONSTRAINT "posts_sites_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."posts_sites"
    ADD CONSTRAINT "posts_sites_site_id_fkey" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."posts_tags"
    ADD CONSTRAINT "posts_tags_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."posts_tags"
    ADD CONSTRAINT "posts_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."promos"
    ADD CONSTRAINT "promos_site_id_fkey" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."sites_categories"
    ADD CONSTRAINT "sites_categories_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."sites_categories"
    ADD CONSTRAINT "sites_categories_site_id_fkey" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."sites_configs"
    ADD CONSTRAINT "sites_configs_site_id_fkey" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."sites_cons"
    ADD CONSTRAINT "sites_cons_con_id_fkey" FOREIGN KEY ("con_id") REFERENCES "public"."cons"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."sites_cons"
    ADD CONSTRAINT "sites_cons_site_id_fkey" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."sites_cryptos"
    ADD CONSTRAINT "sites_cryptos_crypto_id_fkey" FOREIGN KEY ("crypto_id") REFERENCES "public"."cryptos"("id");

ALTER TABLE ONLY "public"."sites_cryptos"
    ADD CONSTRAINT "sites_cryptos_site_id_fkey" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id");

ALTER TABLE ONLY "public"."sites_detail_posts"
    ADD CONSTRAINT "sites_detail_posts_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."sites_detail_posts"
    ADD CONSTRAINT "sites_detail_posts_site_id_fkey" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."sites_payments"
    ADD CONSTRAINT "sites_payments_payment_id_fkey" FOREIGN KEY ("payment_id") REFERENCES "public"."payments"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."sites_payments"
    ADD CONSTRAINT "sites_payments_site_id_fkey" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."sites_pros"
    ADD CONSTRAINT "sites_pros_pro_id_fkey" FOREIGN KEY ("pro_id") REFERENCES "public"."pros"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."sites_pros"
    ADD CONSTRAINT "sites_pros_site_id_fkey" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."sites_tags"
    ADD CONSTRAINT "sites_tags_site_id_fkey" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."sites_tags"
    ADD CONSTRAINT "sites_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."sites_tips"
    ADD CONSTRAINT "sites_tips_site_id_fkey" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."sites_visits"
    ADD CONSTRAINT "sites_visits_site_id_fkey" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON DELETE CASCADE;

CREATE POLICY "Enable insert for authenticated users only" ON "public"."posts_raw" FOR INSERT TO "authenticated" WITH CHECK ((("is_verified" IS FALSE) AND ("author_id" = "auth"."uid"())));

CREATE POLICY "Enable read access for all users" ON "public"."ads" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."categories" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."cons" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."cryptos" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."delivers" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."filters" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."images" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."mails" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."navigations" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."navis" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."payments" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."posts" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."posts_categories" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."posts_secrets" FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."posts_sites" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."posts_tags" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."promos" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."pros" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."sites" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."sites_categories" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."sites_configs" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."sites_cons" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."sites_cryptos" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."sites_detail_posts" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."sites_payments" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."sites_pros" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."sites_tags" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."sites_tips" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."tags" FOR SELECT USING (true);

CREATE POLICY "Enable read access for self posts_raw" ON "public"."posts_raw" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "author_id"));

ALTER TABLE "public"."ads" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."autolinks" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."cons" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."cryptos" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."delivers" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."filters" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."images" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."mails" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."navigations" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."navis" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."payments" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."posts" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."posts_categories" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."posts_raw" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."posts_secrets" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."posts_sites" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."posts_tags" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."promos" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."pros" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."sites" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."sites_categories" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."sites_configs" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."sites_cons" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."sites_cryptos" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."sites_detail_posts" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."sites_payments" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."sites_pros" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."sites_tags" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."sites_tips" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."sites_visits" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tags" ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."create_tags_name_cn"() TO "anon";
GRANT ALL ON FUNCTION "public"."create_tags_name_cn"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."create_tags_name_cn"() TO "service_role";

GRANT ALL ON FUNCTION "public"."generate_uid"() TO "anon";
GRANT ALL ON FUNCTION "public"."generate_uid"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."generate_uid"() TO "service_role";

GRANT ALL ON FUNCTION "public"."update_tag_count"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_tag_count"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_tag_count"() TO "service_role";

GRANT ALL ON TABLE "public"."ads" TO "anon";
GRANT ALL ON TABLE "public"."ads" TO "authenticated";
GRANT ALL ON TABLE "public"."ads" TO "service_role";

GRANT ALL ON SEQUENCE "public"."ads_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ads_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ads_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."autolinks" TO "anon";
GRANT ALL ON TABLE "public"."autolinks" TO "authenticated";
GRANT ALL ON TABLE "public"."autolinks" TO "service_role";

GRANT ALL ON SEQUENCE "public"."autolinks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."autolinks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."autolinks_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."categories" TO "anon";
GRANT ALL ON TABLE "public"."categories" TO "authenticated";
GRANT ALL ON TABLE "public"."categories" TO "service_role";

GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."cons" TO "anon";
GRANT ALL ON TABLE "public"."cons" TO "authenticated";
GRANT ALL ON TABLE "public"."cons" TO "service_role";

GRANT ALL ON SEQUENCE "public"."cons_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cons_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cons_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."cryptos" TO "anon";
GRANT ALL ON TABLE "public"."cryptos" TO "authenticated";
GRANT ALL ON TABLE "public"."cryptos" TO "service_role";

GRANT ALL ON SEQUENCE "public"."cryptos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cryptos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cryptos_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."delivers" TO "anon";
GRANT ALL ON TABLE "public"."delivers" TO "authenticated";
GRANT ALL ON TABLE "public"."delivers" TO "service_role";

GRANT ALL ON SEQUENCE "public"."delivers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."delivers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."delivers_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."filters" TO "anon";
GRANT ALL ON TABLE "public"."filters" TO "authenticated";
GRANT ALL ON TABLE "public"."filters" TO "service_role";

GRANT ALL ON SEQUENCE "public"."filters_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."filters_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."filters_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."images" TO "anon";
GRANT ALL ON TABLE "public"."images" TO "authenticated";
GRANT ALL ON TABLE "public"."images" TO "service_role";

GRANT ALL ON TABLE "public"."mails" TO "anon";
GRANT ALL ON TABLE "public"."mails" TO "authenticated";
GRANT ALL ON TABLE "public"."mails" TO "service_role";

GRANT ALL ON TABLE "public"."navigations" TO "anon";
GRANT ALL ON TABLE "public"."navigations" TO "authenticated";
GRANT ALL ON TABLE "public"."navigations" TO "service_role";

GRANT ALL ON SEQUENCE "public"."navigations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."navigations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."navigations_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."navis" TO "anon";
GRANT ALL ON TABLE "public"."navis" TO "authenticated";
GRANT ALL ON TABLE "public"."navis" TO "service_role";

GRANT ALL ON SEQUENCE "public"."navis_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."navis_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."navis_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."payments" TO "anon";
GRANT ALL ON TABLE "public"."payments" TO "authenticated";
GRANT ALL ON TABLE "public"."payments" TO "service_role";

GRANT ALL ON SEQUENCE "public"."payments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."payments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."payments_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."posts" TO "anon";
GRANT ALL ON TABLE "public"."posts" TO "authenticated";
GRANT ALL ON TABLE "public"."posts" TO "service_role";

GRANT ALL ON TABLE "public"."posts_categories" TO "anon";
GRANT ALL ON TABLE "public"."posts_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."posts_categories" TO "service_role";

GRANT ALL ON SEQUENCE "public"."posts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."posts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."posts_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."posts_raw" TO "anon";
GRANT ALL ON TABLE "public"."posts_raw" TO "authenticated";
GRANT ALL ON TABLE "public"."posts_raw" TO "service_role";

GRANT ALL ON SEQUENCE "public"."posts_raw_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."posts_raw_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."posts_raw_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."posts_secrets" TO "anon";
GRANT ALL ON TABLE "public"."posts_secrets" TO "authenticated";
GRANT ALL ON TABLE "public"."posts_secrets" TO "service_role";

GRANT ALL ON SEQUENCE "public"."posts_secrets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."posts_secrets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."posts_secrets_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."posts_sites" TO "anon";
GRANT ALL ON TABLE "public"."posts_sites" TO "authenticated";
GRANT ALL ON TABLE "public"."posts_sites" TO "service_role";

GRANT ALL ON TABLE "public"."posts_tags" TO "anon";
GRANT ALL ON TABLE "public"."posts_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."posts_tags" TO "service_role";

GRANT ALL ON TABLE "public"."promos" TO "anon";
GRANT ALL ON TABLE "public"."promos" TO "authenticated";
GRANT ALL ON TABLE "public"."promos" TO "service_role";

GRANT ALL ON SEQUENCE "public"."promos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."promos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."promos_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."pros" TO "anon";
GRANT ALL ON TABLE "public"."pros" TO "authenticated";
GRANT ALL ON TABLE "public"."pros" TO "service_role";

GRANT ALL ON SEQUENCE "public"."pros_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pros_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pros_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."sites" TO "anon";
GRANT ALL ON TABLE "public"."sites" TO "authenticated";
GRANT ALL ON TABLE "public"."sites" TO "service_role";

GRANT ALL ON TABLE "public"."sites_categories" TO "anon";
GRANT ALL ON TABLE "public"."sites_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."sites_categories" TO "service_role";

GRANT ALL ON TABLE "public"."sites_configs" TO "anon";
GRANT ALL ON TABLE "public"."sites_configs" TO "authenticated";
GRANT ALL ON TABLE "public"."sites_configs" TO "service_role";

GRANT ALL ON SEQUENCE "public"."sites_configs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sites_configs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sites_configs_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."sites_cons" TO "anon";
GRANT ALL ON TABLE "public"."sites_cons" TO "authenticated";
GRANT ALL ON TABLE "public"."sites_cons" TO "service_role";

GRANT ALL ON TABLE "public"."sites_cryptos" TO "anon";
GRANT ALL ON TABLE "public"."sites_cryptos" TO "authenticated";
GRANT ALL ON TABLE "public"."sites_cryptos" TO "service_role";

GRANT ALL ON TABLE "public"."sites_detail_posts" TO "anon";
GRANT ALL ON TABLE "public"."sites_detail_posts" TO "authenticated";
GRANT ALL ON TABLE "public"."sites_detail_posts" TO "service_role";

GRANT ALL ON SEQUENCE "public"."sites_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sites_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sites_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."sites_payments" TO "anon";
GRANT ALL ON TABLE "public"."sites_payments" TO "authenticated";
GRANT ALL ON TABLE "public"."sites_payments" TO "service_role";

GRANT ALL ON TABLE "public"."sites_pros" TO "anon";
GRANT ALL ON TABLE "public"."sites_pros" TO "authenticated";
GRANT ALL ON TABLE "public"."sites_pros" TO "service_role";

GRANT ALL ON TABLE "public"."sites_tags" TO "anon";
GRANT ALL ON TABLE "public"."sites_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."sites_tags" TO "service_role";

GRANT ALL ON TABLE "public"."sites_tips" TO "anon";
GRANT ALL ON TABLE "public"."sites_tips" TO "authenticated";
GRANT ALL ON TABLE "public"."sites_tips" TO "service_role";

GRANT ALL ON SEQUENCE "public"."sites_tips_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sites_tips_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sites_tips_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."sites_visits" TO "anon";
GRANT ALL ON TABLE "public"."sites_visits" TO "authenticated";
GRANT ALL ON TABLE "public"."sites_visits" TO "service_role";

GRANT ALL ON SEQUENCE "public"."sites_visits_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sites_visits_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sites_visits_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tags" TO "anon";
GRANT ALL ON TABLE "public"."tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tags" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tmr_image_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tmr_image_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tmr_image_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tmr_mail_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tmr_mail_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tmr_mail_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."v_posts" TO "anon";
GRANT ALL ON TABLE "public"."v_posts" TO "authenticated";
GRANT ALL ON TABLE "public"."v_posts" TO "service_role";

GRANT ALL ON TABLE "public"."v_sites" TO "anon";
GRANT ALL ON TABLE "public"."v_sites" TO "authenticated";
GRANT ALL ON TABLE "public"."v_sites" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
