name: Migration

on:
  push:
    branches:
      - main  # 或你使用的分支名

jobs:
  migration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '18.16.0'  # 选择合适的 Node.js 版本
    - name: Docker Info
      run: docker --version
    - name: Install dependencies
      run: npm install supabase  # 或使用 yarn
    - name: Update denpendencies
      run: npm update supabase
    - name: Login Supabase
      run: echo ${{ secrets.SUPABASE_ACCESS_TOKEN }} | npx supabase login
    - name: Link Supabase
      run: npx supabase link --project-ref=elftoojqpqugfbgqxiww
    - name: Supabase migration squash
      run: echo Y | npx supabase migration squash --linked
    - name: Migration Supabase
      run: npx supabase db push --password=${{ secrets.DATABASE_PASSWORD }}
    # # - name: Deploy Supabase Functions
    # #   run: npx supabase functions deploy
